version: '3.8'
services:
  flaskapi:
    build: ./flask
    ports:
      - 5000:5000
    environment:
      FLASK_APP: main.py
      CORS_ORIGINS: "localhost:4200"
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
  fastapi:
    build: ./fast
    command:
      [
        'sh',
        '-c',
        'sleep 20 && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
      ]
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/tagdb?schema=public
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tagdb
