version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - .pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tagdb