version: '3.8'
services:
  flaskapi:
    build: .
    volumes:
      - .:/code
    ports:
      - 5000:5000
    environment:
      FLASK_APP: main.py
      CORS_ORIGINS: "localhost:4200"
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local